services:
  - type: web
    runtime: node
    name: ris-landingpage
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/analytics.db
    disk:
      name: analytics-data
      mountPath: /var/data
      sizeGB: 1
