services:
  - type: web
    runtime: node
    name: ris-landingpage
    repo: https://github.com/mbanner77/rislanding.git
    branch: main
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/analytics.db
    disk:
      name: analytics-data
      mountPath: /var/data
      sizeGB: 1
